src/main/bash/gvm-current.sh, src/main/bash/gvm-init.sh
Related to https://github.com/gvmtool/gvm-cli/pull/300
=> Removes GVM_CANDIDATE_COUNT

Dockerfile, README.md
I've needed Docker to pass tests.
=> Add Dockerfile for tests

Dockerfile, README.md, src/main/bash/sdkman-list.sh, src/main/bash/sdkman-utils.sh
The commits are fairly separate, but all oriented around getting the tests working more reliably on Docker.
There is still one test failing on my machine, but I can't figure out why yet.
=> Improve the testing in Docker.

src/main/bash/sdkman-path-helpers.sh
mklink function from: http://stackoverflow.com/questions/3343988/accessing-a-cygwin-symlink-from-windows/11166347#11166347
=> Fix creating symlinks in cygwin

src/main/bash/sdkman-init.sh
=> get rid of gvm alias related code

src/main/bash/sdkman-selfupdate.sh
Normalize confirm question with other confirm questions in project. Ie. using colon and space after
Before
Would you like to upgrade now? (Y/n)y
After:
Would you like to upgrade now? (Y/n) : y
This addresses Issue #XXX
=> Update formatting of confirm text

src/main/bash/sdkman-list.sh
This addresses Issue #163
@marc0der asked for a PR to fix this issue. Today we had a [Hackergarten](http://hackergarten.net) in Berne and selected this issue to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sdkman/sdkman-cli/616)
=> Skip all files in versions listing #163

src/main/bash/sdkman-list.sh
Just swapped the parameters of the `find` command.
This addresses Issue #163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sdkman/sdkman-cli/617)
=> Linux find is somewhat sensitive to the order of the parameters.

src/main/bash/sdkman-init.sh
In my tests, this reduces execution time by about 50% with `bash`,
and 40% with `zsh`. Most of the speedup is from removing calls to
external commands like `basename` and `cat`.
This addresses Issue #624.
=> sdkman-init.sh: various optimizations and cleanup

src/main/bash/sdkman-uninstall.sh
=> change sed delimiter to safe character

src/main/bash/sdkman-env.sh, src/test/cucumber/per_project_configuration.feature, src/test/groovy/sdkman/specs/EnvCommandSpec.groovy, src/test/groovy/sdkman/steps/env_steps.groovy, src/test/groovy/sdkman/support/UnixUtils.groovy
=> Add sdk env command to support per-project configuration

src/test/groovy/sdkman/steps/installation_steps.groovy, src/test/groovy/sdkman/steps/stub_steps.groovy
Multiple tests were failing on macOS because of test bugs related to the platform.
Please see each commit message for the issue that was fixed by that commit.
=> PR 1: Testing platform bug fixes

src/main/bash/sdkman-install.sh
Fix typo in debug echo in __sdkman_download
=> PR 5: Fix typo in debug echo in __sdkman_download

src/main/bash/sdkman-path-helpers.sh
Use relative path for current symlink to version dir
=> Use relative path for current symlink to version dir

src/main/bash/sdkman-availability.sh, src/main/bash/sdkman-cache.sh
=> Replace $(cat file) invocations with $(< file) for better performance

src/main/bash/sdkman-init.sh, src/test/groovy/sdkman/specs/EnvCommandSpec.groovy
=> Run sdk env on opening a new terminal

.gitignore, src/main/bash/sdkman-install.sh, src/test/cucumber/install_candidate.feature, src/test/cucumber/local_developement_versions.feature, src/test/cucumber/service_unavailable.feature
=> Do not return error when package is already installed

.gitignore, src/main/bash/sdkman-flush.sh, src/main/bash/sdkman-help.sh, src/test/cucumber/flush.feature
- flush all -> flush broadcast, flush archives and flush temp
This addresses Issue #XXX
=> Convenience method "sdk flush all"

src/main/bash/sdkman-env.sh, src/main/bash/sdkman-help.sh, src/main/bash/sdkman-init.sh, src/test/groovy/sdkman/specs/EnvCommandSpec.groovy, src/test/groovy/sdkman/steps/initialisation_steps.groovy, src/test/resources/features/per_project_configuration.feature
Fixes #824 
Please note that the changes introduced here could use some refactor. However at the time of submitting this work there's an ongoing PR #785 overlapping with this one and addressing just that. Therefore I'd rather wait to see it progress instead of repeating the same work.
=> Add `sdk env clear` subcommand

src/main/bash/sdkman-init.sh, src/test/groovy/sdkman/specs/EnvCommandSpec.groovy
=> Check if the .sdkmanrc in the current directory has already been applied

src/main/bash/sdkman-env.sh, src/test/resources/features/per_project_configuration.feature
=> Add `sdk env install` subcommand

src/main/bash/sdkman-init.sh, src/test/groovy/sdkman/specs/EnvCommandSpec.groovy
=> Export SDKMAN_OLD_PWD unconditionally

src/main/bash/sdkman-edit.sh, src/main/bash/sdkman-main.sh, src/test/groovy/sdkman/specs/EditCommandSpec.groovy
=> Add edit command

contrib/completion/bash/sdk
=> Add autocompletion for use subcommand

.travis.yml, contrib/completion/zsh/sdk, src/main/bash/sdkman-completion.sh
Adds zsh completion under the `completion` command. This is based on the original completion script contributed to oh-my-zsh by @rgoldberg
=> Add zsh completion.

src/main/bash/sdkman-main.sh
Fixes https://github.com/sdkman/sdkman-cli/issues/681.
=> Fix update warn on new shells for update cmd

src/main/bash/sdkman-env-helpers.sh, src/main/bash/sdkman-init.sh, src/test/groovy/sdkman/specs/PlatformSpec.groovy, src/test/groovy/sdkman/steps/env.groovy, src/test/groovy/sdkman/steps/initialisation_steps.groovy, src/test/groovy/sdkman/steps/stub_steps.groovy, src/test/groovy/sdkman/stubs/UnameStub.groovy, src/test/groovy/sdkman/support/UnixUtils.groovy, src/test/resources/features/java_installation.feature
Cleans up platform inference in the tests.
=> Further cleanup around platform inference

contrib/completion/bash/sdk
This PR adds Bash completion for `sdk install`.
=> Add completion for sdk install

src/main/bash/sdkman-current.sh, src/main/bash/sdkman-use.sh
=> Use match instead of BASH_REMATCH when using zsh

src/main/bash/sdkman-env.sh, src/test/resources/features/per_project_configuration.feature
=> Make the `env install` command set the shell versions

contrib/completion/bash/sdk
=> Updates for missing completions - #909

src/main/bash/sdkman-main.sh
=> Forgo all checks when running __sdk_completion

.github/workflows/release.yml, .github/workflows/run.yml, build.gradle
Introducing Github actions for the CLI :tada:
=> Rename github workflow

src/main/bash/sdkman-init.sh
* Resolves issue #947 with gcloud sdk completions not working
=> Prevent Re-initialization of zsh completion system

src/main/bash/sdkman-flush.sh, src/main/bash/sdkman-install.sh, src/test/groovy/sdkman/env/SdkmanBashEnvBuilder.groovy, src/test/groovy/sdkman/steps/env.groovy, src/test/groovy/sdkman/steps/flush_steps.groovy, src/test/groovy/sdkman/steps/installation_steps.groovy, src/test/resources/features/flush.feature, src/test/resources/features/install_candidate.feature
Store the HTTP response headers for each downloaded candidate. 
These headers will be used in future PRs to extract metadata such as: checksums, file type, file name, etc.
=> Save HTTP response headers under ${SDKMAN}/var/metadata

.gitignore, src/main/bash/sdkman-help.sh, src/main/bash/sdkman-install.sh, src/test/groovy/sdkman/steps/stub_steps.groovy, src/test/groovy/sdkman/stubs/WebServiceStub.groovy, src/test/resources/features/checksum_verification.feature
SHA checksums using perl's `shasum` utility
=> SHA checksums

contrib/completion/bash/sdk, gradle/archive.gradle, src/test/groovy/sdkman/env/SdkmanBashEnvBuilder.groovy, src/test/groovy/sdkman/specs/CompletionSpec.groovy
Because Bash completion breaks regularly I've added a few tests for the most critical completions for
* sdk
* sdk install
* sdk install java
=> Add tests for Bash programmable completion

src/main/bash/sdkman-install.sh, src/test/groovy/sdkman/steps/flush_steps.groovy, src/test/resources/features/checksum_verification.feature, src/test/resources/features/flush.feature, src/test/resources/features/install_candidate.feature
Issue https://github.com/sdkman/sdkman-cli/issues/1005
=> Fix bug when reinstalling a candidate (checksums for cached archives)

.github/workflows/release.yml, src/jreleaser/changelog.tpl
Remove placeholder text from changelog template
Changelog generation pulls full history
=> Update JReleaser configuration

src/main/bash/sdkman-install.sh, src/test/resources/features/checksum_verification.feature
Add feature flag to disable checksumming
=> "sdkman_checksum_skip" feature flag

gradle/release.gradle
/cc @marc0der Disables Homebrew for the time being.
=> Disable Homebrew packager

gradle/release.gradle
=> Enable Homebrew packager

gradle/release.gradle
Add an explicit platform which the Homebrew packager requires.
=> Add platform to appease Homebrew packager

build.gradle
=> Upgrade JReleaser to 1.0.0-M3

src/jreleaser/distributions/sdkman-cli/brew/README.md.tpl
Just some minor fixes to the generated Homebrew README.
=> Improve Homebrew README

build.gradle, gradle/release.gradle
This one is for you @aalmiray 😄!
=> Bump JReleaser from 1.0.0-M3 to 1.0.0

src/test/groovy/sdkman/support/UnixUtils.groovy
=> Fix test failures in OSX/Intel when inferring the platform
