sdkman/sdkman-cli

src/main/bash/gvm-outdated.sh

Sorry, but the current outdated command can't print the "Outdated" label properly in some case: In order, the first candidate is not outdated, but the after-second candidate is outdated.
It's caused by the wrong condition.

Fix the issue that the "Outdated:" label is not displayed in some cases.

---

src/main/bash/gvm-current.sh

__gvmtool_determine_current_version currently has ".gvm" hardcoded instead of using the GVM_DIR env var, this pull request fixes that.

Use ${GVM_DIR} instead of hardcoded .gvm

---

src/main/bash/gvm-init.sh
src/test/groovy/gvm/specs/InitialisationSpec.groovy

In bash, `${#ARR}` returns the length of the string in the first slot.
'asciidoctorj' has a length of 12, which was working until more
candidates were added.
`${#ARR[*]}` is the correct way to return the length of an array in
bash. Thankfully, this works in ZSH as well.
This issue is preventing `vertx` from appearing on my path.
To demonstrate, you may run these commands in your shell:
```
$ echo ${GVM_CANDIDATES[*]}
asciidoctorj crash gaiden glide gradle grails griffon groovy groovyserv 
jbake jbossforge lazybones springboot vertx
$ echo ${#GVM_CANDIDATES}
12
$ echo ${#GVM_CANDIDATES[*]}
14
```

Fix init from missing the last few candidates

---

README.md

That folder was renamed in here febef222e610040b8619efed02cdbad9d99ed56e

Fix 'Running the server locally' section in Readme.md

---

src/main/bash/sdkman-outdated.sh

Before, there were empty candidates directories even if it's not installed. Now, there are no directories of candidates which isn't installed. So you should fix it.
```
$ sdk outdated
find: /Users/nobeans/.sdkman/candidates/asciidoctorj: No such file or directory
find: /Users/nobeans/.sdkman/candidates/crash: No such file or directory
find: /Users/nobeans/.sdkman/candidates/griffon: No such file or directory
```

Fix "find: xxx: No such file or directory" error when using 'outdated' command

---

src/main/bash/sdkman-utils.sh

I execute sdk command(Ex: "sdk list groovy"). But it could not run.
The shell had an error.
```
__sdkman_path_contains:local:2: not valid in this context: (x86)/MacType:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program
Files=''
Files=''
Files=''
Files=''
Files=''
Management=''
Engine=''
Files=''
Management=''
Engine=''
Files=''
Management=''
Engine=''
Files=''
Files=''
SQL=''
Files=''
Files=''
```
So I fixed this bug.
It occurred because there is no double quotes in the path. Cygwin path is included windows system path("Program Files","Program Files(x86)").

Fix "not valid in thes context" when working with Cygwin

---

src/main/bash/sdkman-list.sh

A simple change to respect the PAGER environment variable. This allows other pagers besides "less" to be used.  Additionally, it allows paging to be turned off entirely by setting PAGER to cat.
If PAGER is unset, it defaults to less, so the default behavior is unchanged.

Allow other pagers besides "less" to be used.

---

src/main/bash/sdkman-init.sh

the missing `unset i` causes issues in zsh if you use the variable `i` in your
own code outside sdkman

fixing similar issue to #232 `unset i`

---

src/test/groovy/sdkman/env/CleanBashEnvBuilder.groovy
src/test/groovy/sdkman/specs/InstallSpec.groovy
src/test/groovy/sdkman/stubs/WebServiceStub.groovy
src/test/groovy/sdkman/utils/WireMockServerProvider.groovy
src/test/steps/sdkman/broadcast_steps.groovy
src/test/steps/sdkman/env.groovy
src/test/steps/sdkman/initialisation_steps.groovy
src/test/steps/sdkman/stub_steps.groovy

Apparently it's not possible to add afterAll hooks into cucumber groovy. That means that as a Wiremock instance is created on startup on 8080 if you want to use Wiremock in non-cucumber tests you have two options: 
1. Creating another Wiremock instance in another port.
2. Reusing previous instance.
First solution is not doable as current setup relies on `prepareTestScripts` gradle task. Install script has the following reference, `SDKMAN_SERVICE="@SDKMAN_SERVICE@"`, that means than even if we set `SDKMAN_SERVICE` to `http://localhost:8081` at `CleanBashEnvBuilder` the value will be overridden by the one set up at `build.gradle`. That's why `CleanBashEnvBuilder` is not even setting up those variables. 
Therefore this PR goes with second proposed option.

FEATURE #388 - First spec for install script.

---

src/test/groovy/sdkman/specs/InstallSpec.groovy

This PR won’t tackle tests relying on tooling installed on the host machine. Current solution for using a Java process that wraps a bash session has the following shortcomings:
- Current bash isolation boundaries are not enough ambitious. Those boundaries are the filesystem, as every file that will be manipulated by SDKMAN production scripts will be isolated in some tmp folder. However there is no isolation (or dependency injection) regarding Unix tooling used by those scripts. If we delete one of those tools (testing that unzip is not present in the system), we’ll mess with the host environment.
- Unix tooling are slightly different in BSD and GNU. That means that these tests are currently OS dependant creating brittle test suites or code that is not tested from a portability point of …

FEATURE #388 - Add more specs for install script.

---

src/main/bash/install.sh

should fix #282
If you have existing dotfiles setup, `~/.sdkman/etc/config` is already present (as a symlink).

check for `bin` dir inside SDKMAN_DIR to check previous installation

---

src/main/bash/sdkman-current.sh

This fixes an issue where the entire path was being added for the current
version if the candidate itself was on the path, but not part of SDKMAN
path
Fixes #422

Update Path check to include SDKMAN path

---

src/main/bash/sdkman-path-helpers.sh

This reverts commit e3a4d4691845ecbc658fb420d7e3fc60a2491396.
This fixes issue #467. Cygwin can be configured to do what this commit did
by setting the following `export CYGWIN=winsymlinks:native`

Revert "Fix creating symlinks in cygwin (#302)"

---

src/main/bash/sdkman-help.sh

The help lists akka as one of the candidates, which is weird, because it is not.
This change fixes that by replacing with gradle.
If there is a list of most popular things installed using sdkman, I can replace the list with things from that.

Remove akka from list of candidates in help

---

src/main/bash/sdkman-install.sh

First of all, the proposed change might not be the best solution and I have only tested it in Ubuntu.
I've been using `sdkman` for a while and I also use it in Ansible scripts while configuring a development environment. I hadn't had any issues so far but just recently it seemed to stop working. It basically hanged indefinitely while executing `sdk install XXX` commands through Ansible scripts, while running them directly from the shell worked well as usual.
I googled "bash stuck ansible" and found this: https://github.com/ansible/ansible/issues/12459
It didn't seemed related at the time but while reviewing the latest 'sdkman-cli` commits I saw something familiar: https://github.com/sdkman/sdkman-cli/commit/e37872123d6b48ed2784d1ab9219fa6c3cacc17f
It appears that using `cat /dev/urandom` …

Change random string generation to be Ansible friendly

---

src/main/bash/sdkman-utils.sh

`which less` has the following output in some versions of Bash:
less is /usr/bin/less
`command -v less` outputs the path, but unfortunately has non-executable output in the case of aliases:
$ alias less='my-super-less'
$ command -v less
alias less='my-super-less'
In this change, we use the exit code, not the output. (Thanks @halyph.)
Closes #493.

Don't use the output of `which` or `command -v`.

---

src/main/bash/sdkman-outdated.sh
src/test/cucumber/outdated_candidate.feature

The purpose of this PR is to provide a way to update all the outdated candidates and set them as the default version.
When running `sdk outdated`, with or without a specific candidate, and only if there is any outdated candidate, ask the user for confirmation on updating all of them and setting them as the default, and do so accordingly.

Outdated command can update all outdated candidates

---

src/main/bash/sdkman-help.sh
src/main/bash/sdkman-install.sh
src/main/bash/sdkman-main.sh
src/main/bash/sdkman-upgrade.sh
src/test/cucumber/mnemonics.feature
src/test/cucumber/upgrade_candidate.feature

Attempt to rename `outdated` command to `upgrade`. I've made two commits to ease the review:
1. 4dda1bf4f52f8138b449a48ed8538c99d719818e Actual command renaming
2. 8b9138268eecb6671ce109fc0ac3494674444f95 Renaming files containing `outdated`
Since mnemonic `u` is already used by the `use` command, I've proposed `g` as the mnemonic for `upgrade`.
I've kept backwards compatibility for `outdated` command and its mnemonic `o`.
*Edit:* Finally `upgrade` mnemonic has been set to `ug`

Rename outdated to upgrade

---

src/main/bash/sdkman-init.sh

This reverts commit 05bb6d4c4a5da466b94ed1a01dedcfd0746a357a.
Changing the $IFS causes issues on some systems:
"Yesterday I updated sdkman to 5.3.0+159, and now I can not login to
OS (ubuntu 16.10)"

Revert "Fix IFS backup bug."

---

etc/README.md
etc/sdk.zsh_completion

This PR aims to provide `zsh` completion for the `sdk` command.
Many completions are provided as `zsh` plugins through `oh-my-zsh`, although I find it more convenient to have them in each project. This way, both the project and the completions can evolve accordingly instead of relying on the plugin author to keep the completions up to date.
Other projects such as [hub](https://github.com/github/hub) or [docker-compose](https://github.com/docker/compose) manage `zsh` completions this way.

Add zsh completion

---

src/main/bash/sdkman-upgrade.sh

The `upgrade` command doesn't work properly in `zsh` due to the different nature on array assignations.
I couldn't find a more elegant way to do it. This is the only place in the whole codebase where the `SDKMAN_CANDIDATES` array is not directly accessed but assigned to a local variable (in order to reuse the upgrade code for the single candidate vs. all candidates scenarios).

Make upgrade command bash/zsh compatible

---

src/main/bash/sdkman-utils.sh

PAGER may contain arguments.  See `man 1 man` for details.  See `man bash` for the explanation of `eval`.
This addresses Issue #594

Properly evaluate command from PAGER string

---

src/main/bash/sdkman-init.sh

for clarity I've tried to make update of cache to be more "transactional" so renamed working SDKMAN_CANDIDATES_CSV to SDKMAN_FRESH_CANDIDATES_CSV during the download and validation

fix for 598

---

src/main/bash/sdkman-utils.sh

The previous bash version check, `bash --version | grep ... `, may not work when the output is not in English (for example, it didn't work when the output was in Italian). 
For the same reason, I've modified also the line 113, to output the first command output of `bash --version` without checking for the content.
This addresses Issue #649

Refine bash major version check

---

src/main/bash/sdkman-install.sh
src/test/cucumber/local_developement_versions.feature

For installing local development versions validate the length doesn't exceed 15 char which will end up being truncated in the list view.
This Addresses Issue #619

Validate Version on Local Install

---

src/main/bash/sdkman-init.sh
src/main/bash/sdkman-install.sh
src/main/bash/sdkman-utils.sh

support `curl` options related to retry which might be useful in poor network connection conditions.
This addresses Issue #632

download with retry

---

src/main/bash/sdkman-availability.sh
src/main/bash/sdkman-cache.sh

Setting 'noclobber' in bash or zsh prevents writing to an existing
regular file when using > as redirecting operator. Setting 'noclobber' allows
users of interactive shells to prevent accidential overwriting of
existing files.
bash and zsh allow to use >| as redirection operator so that the
redirection is attempted.
Because the write to the status files is required and not by accident
the >| is used in those cases.
This addresses Issue #669

Use '>|' to write var/ status files

---

src/main/bash/sdkman-help.sh

Updated help script with 4th `install` argument; an optional path to a local installation (for adding `local` versions). This resulted from a conversation held in issue #673.

Update help script with local installation path argument.

---

src/main/bash/sdkman-update.sh
src/main/bash/sdkman-utils.sh

IntelliJ auto-formatting inexplicably failed to append parentheses after
function names in certain bash files.  Fixed this.

PR 2.5: Append parentheses after bash function names

---

bin/release.sh
src/main/bash/sdkman-cache.sh
src/main/bash/sdkman-uninstall.sh
src/test/cucumber/home.feature
src/test/cucumber/java_installation.feature
src/test/cucumber/service_unavailable.feature
src/test/cucumber/uninstall_candidate.feature
src/test/groovy/sdkman/specs/CandidatesCacheUpdateSpec.groovy
src/test/resources/__files/hooks/post_hook_java_8.0.101_linux64.sh

Includes commits for all previous PRs in my sequential PR series.
Fixed misspelled words.

PR 4: Spelling

---

src/main/bash/sdkman-install.sh
src/main/bash/sdkman-update.sh
src/test/groovy/sdkman/env/BashEnv.groovy

Using the '>|' syntax for shell redirections instead of '>' forces an
overwrite even if the noclobber option is set.
This addresses Issue #484.
I've added the `-o noclobber` option to the bash test environment and confirmed that without my changes some of the tests fail, while with my changes they all pass. This also prevents regressions in case someone adds another redirection later that doesn't use `>|`.
Since I use zsh myself I can confirm that it works there as well.

Don't fail redirections if noclobber is set

---

src/main/bash/sdkman-update.sh
src/test/cucumber/update.feature

In `__sdk_update`, candidates wouldn't be updated if the same number of
candidates were removed & added because detection was solely based on
old vs. new candidate counts.

PR 6: Candidate cache update bug

---

src/main/bash/sdkman-update.sh
src/test/groovy/sdkman/specs/CandidatesCacheUpdateFailureSpec.groovy

Fix cached candidate server api error-handling bug in `__sdk_update`, plus a few other improvements to `__sdk_update`.

Fix cached candidate server api error-handling bug in sdk update

---

src/main/bash/sdkman-init.sh

Simplify bash csv parsing in `sdkman-init.sh` by changing `IFS` just for one command, like what was done recently in `sdkman-update.sh`.

Simplify bash csv parsing in sdkman-init.sh

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_request.md
.github/pull_request_tempalte.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Issues are either a bug report, feature request or support request. Labels
are automaticaly added to the issues respectively: bug, enhancement, support.
The templates suggest using the Slack before opening an issue, but no longer
say it is a hard requirement. This might give a more inclusive impression to
people reporting who are not Slack users.
This addresses Issue #753
CONTRIBUTING.md was also rephrased.
The tag 'support' would be new. We could not set a tag there. Or even rephrase the text to be more 'We do not want to offer support via GitHub AT ALL', if requested.
I have set it to the default branch of my fork, so you can test how it looks via this repository: https://github.com/draget-forks/sdkman-cli (feel free to create test-issues or PRs in there!)

Add GitHub issue templates for bugs, features, support and PRs

---

src/main/bash/sdkman-utils.sh

Sequence curl arguments using array instead of scalar in `__sdkman_secure_curl_download`:
- Code is now shell-agnostic
- Fixes argument concatenation bugs

Improve __sdkman_secure_curl_download

---

src/main/bash/sdkman-update.sh
src/main/bash/sdkman-utils.sh

Remove legacy bash workaround from `__sdk_update`.
The code that didn't work on legacy bash was removed a long time ago, so the workaround is no longer necessary.
The workaround prevents 4 or so tests from completing successfully on legacy bash, so it's very useful to remove the workaround, so we can run the test suite on bash 3.2.x.

Remove legacy bash workaround from __sdk_update

---

src/test/cucumber/path_initialisation.feature

Rename duplicate path initialisation scenario name.
Two scenarios both had the same name. Renamed the incorrectly named one.

Rename duplicate path initialisation scenario name

---

src/main/bash/sdkman-path-helpers.sh

When working with git bash it ends up with an error saying it cannot remove the directory 'current' adding the -R will solve it for both nix and win.

Add support to Git Bash (switch default)

---

src/main/bash/sdkman-env-helpers.sh
src/test/resources/features/java_installation.feature

The console will now display additional text describing a helpful command if installation fails due to incorrect verison provided.

#827: Add a helpful tip when incorrect version is provided while installation

---

src/main/bash/sdkman-init.sh

I use zsh and also make use of a [zmodule](https://github.com/zdharma/zinit#zinit-module) that compiles sourced files for faster execution. This compilation produces binary blobs which end in `.zwc`.
The change proposed here is to make sure sdkman only sources the `.sh` files and nothing else, otherwise it will keep producing errors at startup.
My current work-around is to redirect stderr, but I think adding the `.sh` suffix makes more sense.

source only files ending with .sh

---

src/main/bash/sdkman-help.sh

Adds the new `sdk env install` command to the usage instructions.

Add `sdk env install` to usage instructions

---

bin/download.sh
src/main/bash/sdkman-flush.sh
src/main/bash/sdkman-install.sh
src/test/groovy/sdkman/stubs/HookResponses.groovy
src/test/resources/__files/hooks/post_hook_java_8.0.111_universal.sh

I'm trying to fix the following:
```sh-session
❯ sdk install java
==== BROADCAST =================================================================
* 2021-01-07: mvnd 0.3.0 available on SDKMAN! https://git.io/JLxCq
* 2021-01-06: micronaut 2.2.3 available on SDKMAN!
* 2021-01-04: gradle 6.8-rc-5 available on SDKMAN!
================================================================================
Downloading: java 11.0.9.hs-adpt
In progress...
################################################################################################################################ 100.0%################################################################################################################################ 100.0%
Repackaging Java 11.0.9.hs-adpt...
Done repackaging...
rm: remove regular file …
```

Fix rm asking to remove file on some zsh

---

src/main/bash/sdkman-default.sh
src/main/bash/sdkman-home.sh
src/main/bash/sdkman-use.sh
src/test/resources/features/default_version.feature
src/test/resources/features/home.feature
src/test/resources/features/use_version.feature

The message now adds an `sdk install` command to inform user how to correct the error.
This is useful when auto env is enabled, and user not aware their colleague has updated the candidate version. In some situation user isn't even aware of the presence of sdkman. All they see was just `Stop! java 15.0.2.fx is not installed`.
See more discussion about this PR in [this Slack thread](https://sdkman.slack.com/archives/CJK9DMV6V/p1611405973006900)

Improved error message when candidate version not found

---

contrib/completion/bash/sdk
src/main/bash/sdkman-config.sh
src/main/bash/sdkman-help.sh
src/test/groovy/sdkman/specs/ConfigCommandSpec.groovy

This PR adds the `edit` command to the `help` output and the Bash completion.

Add edit command to help output and Bash completion

---

src/main/bash/sdkman-init.sh
src/test/groovy/sdkman/specs/EnvCommandSpec.groovy

The previous logic did not clear the environment when the user switches between two directories with `.sdmanrc`.
Now we always clear (if an environment was set), and _then_ load the new one, if any.

Fix: always env clear when leaving dir

---

src/main/bash/sdkman-current.sh
src/main/bash/sdkman-use.sh
src/test/groovy/sdkman/stubs/UnameStub.groovy

Relates to #873.
After thinking a little bit about it, I had an idea to
* make the tests more deterministic
* remove platform specific code, which prevented the first point
A nice side effect of this change is, that a lot of commands (use, install, current) are also a little faster (around 90ms faster).

Remove platform specific code, make tests more deterministic

---

src/main/bash/sdkman-config.sh
src/test/groovy/sdkman/specs/ConfigCommandSpec.groovy

```sh-session
❯ echo $EDITOR
code --wait
❯ sdk config
No default editor configured.
Please set the default editor with the EDITOR environment variable.
```
The fix is to simply remove the double quotes, so the spaces in the env var expand as arguments instead of being interpreted as the path for the executable.

Fix config command when using vscode

---

contrib/completion/bash/sdk

bash-4 does not support process substitution

fix for bash-4 (#923)

---

src/main/bash/sdkman-main.sh
src/main/bash/sdkman-selfupdate.sh
src/test/resources/features/self_update.feature

This also deprecates the auto_selfupdate config.
The automatic version check makes the things a lot harder to script in non-attended environments -- such as CI, as it keeps waiting for a response if an updated version is found.
Also, I use [my own tool to manage my updates system widely](https://github.com/felipecrs/dotfiles/blob/12d6701733071553fbe39c03cee3581e676d64c4/dot_local/bin/executable_full-upgrade#L148), which I run automatically. 
Fixes #925
Depends-On: https://github.com/sdkman/sdkman-hooks/pull/28
Depends-On: https://github.com/sdkman/sdkman-website/pull/49

Add selfupdate_enable config and respect auto_answer when auto updating

---

contrib/completion/bash/sdk

bash-4 does not support process substitution.
Another occurence.

fix for bash-4 (sdkman#923)

---

.github/workflows/beta.yml
.github/workflows/pr.yml
.github/workflows/release.yml

On forks:
* Run beta workflow without any release sections
* Do not run release workflow at all
Also, update workflows to use sdkman GH action to set Java version to Semeru 11.0.12

Only run select GH steps and workflows on forks

---

src/main/bash/sdkman-init.sh

This PR provides a fix for #938 by considering the environment variable `ZSH_DISABLE_COMPFIX`.
By default, on initialization `compinit` is called like before. That means `compaudit` is called and security checks are performed. This might block the shell, waiting for user input. Especially this is not desired in the presence of non-interactive shells. Another scenario, in which security checks might not be desired is a multi-user system. For security reasons, `compinit` requires completion directories to be owned by the same user who runs the command.
If we set `ZSH_DISABLE_COMPFIX="true"`, then `compinit -u -C` is called. Effectively, `-C` will skip all security checks and `-u` will use all files found for completion (see [compinit](https://github.com/zsh-users/zsh/blob/82ff9f24f170eea7daa …

Considering env var ZSH_DISABLE_COMPFIX during initialization

---

contrib/completion/bash/sdk
src/test/groovy/sdkman/env/BashEnv.groovy

Tests are now run with the `--posix` flag by default, to detect cases where something would break in POSIX mode.
Strangely enough, POSIX mode does not disable all of Bash's functionality, so things like `here strings` work. And on Bash 5.x, even process substitution works 😕.

Make Bash completion work with POSIX mode

---

.github/workflows/release.yml
build.gradle
gradle/release.gradle
settings.gradle
src/jreleaser/changelog.tpl

Adds JReleaser configuration in a secondary script named `release.gradle`
Updates the `release.yml` workflow to tag, release, and tweet. It's now triggered as a workflow dispatch, taking the release version as input.
The ` src/jreleaser/changelog.tpl ` template file may be updated before a release to accommodate additional release notes besides the full changelog.

Configure releases via JReleaser

---

src/test/groovy/sdkman/env/BashEnv.groovy

Add /usr/local/bin to default PATH, so user-installed utils (like md5sum in OSX) are picked up during tests

Add /usr/local/bin to test PATH

---

src/main/bash/sdkman-install.sh

On the download of a binary, the curl headers dump is now written to a temporary file. In retrospect, we sanitise this before writing it to the `~/.sdkman/var/metadata` folder. Only lines starting with `X-Sdkman` will now be recorded.

Sanitise noise from metadata headers file

---

.github/workflows/release.yml
gradle/release.gradle
src/jreleaser/distributions/sdkman-cli/brew/README.md.tpl

Some last fixes to allow distribution via Homebrew.

Prepare homebrew distribution

---

src/jreleaser/distributions/sdkman-cli/brew/formula.rb.tpl

@marc0der Just tried to install SDKMAN! via Homebrew and there is still some tiny error which prevents installing it.
{{projectVersion}} was expanded without quotes, resulting in the number `5.14.2` which not even in Ruby is a valid number :D.
I'm now using the `version` attribute, which contains the correct version.

Replace template tag with version

---

.github/dependabot.yml

This PR will make sure that GH Actions are always up to date.

Keep GitHub Actions up to date using Dependabot

---

.github/workflows/beta.yml

/cc @marc0der This one is for you :).
This basically prevents triggering beta releases on workflow changes.

Do not trigger beta releases on changes to GH workflows

---

src/main/bash/sdkman-init.sh

Remove double semicolon problem
Without this fix there may be a message with double semicolon:
bash: PROMPT_COMMAND: line 0: `history -a; history -n; ;sdkman_auto_env'

#1087 Fix sdkman_auto_env when PROMPT_COMMAND ends with semicolon

---

src/main/bash/sdkman-main.sh

These are steps to improve the main `sdk` function to delegate to the currently available native commands.
- Remove home command hack
- Remove legacy completion command workaround
- Display native help falling back to legacy help
- Give precedence to native home command
- Propagation of up to ten params to a native command

Fix main function for native commands

---

src/main/bash/sdkman-env.sh
src/test/groovy/sdkman/specs/EnvCommandSpec.groovy

This change improves `sdk env`'s error handling and displays the correct step to take in case one or more dependencies are not found.
/cc @marc0der

chore: Improve `sdk env` error handling

---

.github/workflows/beta.yml
.github/workflows/pr.yml
.github/workflows/release.yml
gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle to 8.0.1 and sets up Gradle caching for `actions/setup-java@v3` steps.

chore: Upgrade to Gradle 8.0.1, setup caching for GH workflows

---

src/main/bash/sdkman-install.sh

This PR resolves issues when SDKMAN_DIR has whitespaces (see https://github.com/sdkman/sdkman-cli/issues/1208).

Add missing quotes when handling file paths within install command
